### ISSUE TITLE
Pas de fichiers copiés après lancement du script

### ISSUE THREAD

**Issue by Chwarma** [kwyxz/GetWindowsWallpapers#1]
Bonjour Kwyxz (ou Benjamin, si je peux t'appeler comme ça), on a discuté un peu sur Twitter. Je t'ai dit que ton script ne fonctionnait pas sur mon ordinateur. J'ai lancé le script depuis Powershell en administrateur et voila le message que j'ai eu

PS C:\users\nanou\downloads> .\GetWindowsWallpapers.ps1
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:129 : 19
+ </a>              </li>
+                   ~
L’opérateur « < » est réservé à une utilisation future.
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:133 : 19
+ </a>              </li>
+                   ~
L’opérateur « < » est réservé à une utilisation future.
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:138 : 19
+ </a>              </li>
+                   ~
L’opérateur « < » est réservé à une utilisation future.
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:143 : 19
+ </a>              </li>
+                   ~
L’opérateur « < » est réservé à une utilisation future.
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:147 : 19
+ </a>              </li>
+                   ~
L’opérateur « < » est réservé à une utilisation future.
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:609 : 227
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
Le caractère perluète n’est pas autorisé. L’opérateur & est réservé à une utilisation future. Placez un caractère
perluète entre guillemets doubles ("&") pour que ce symbole soit considéré comme une chaîne.
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:612 : 10
+ </form>  </div>
+          ~
L’opérateur « < » est réservé à une utilisation future.
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:628 : 24
+       <li class="mr-3">&copy; 2018 <span title="0.15774s from unicorn ...
+                        ~
Le caractère perluète n’est pas autorisé. L’opérateur & est réservé à une utilisation future. Placez un caractère
perluète entre guillemets doubles ("&") pour que ce symbole soit considéré comme une chaîne.
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:628 : 36
+       <li class="mr-3">&copy; 2018 <span title="0.15774s from unicorn ...
+                                    ~
L’opérateur « < » est réservé à une utilisation future.
Au caractère C:\users\nanou\downloads\GetWindowsWallpapers.ps1:628 : 42
+ ...  2018 <span title="0.15774s from unicorn-973773134-t4h8p">GitHub</spa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Jeton inattendu « title="0.15774s from unicorn-973773134-t4h8p">GitHub</span> » dans l’expression ou l’instruction.
Les erreurs d’analyse n’ont pas toutes été signalées. Corrigez les erreurs signalées, puis recommencez.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported

Si tu as l'occasion d'y jeter un oeil, ce serait cool. Si tu n'as pas le temps ou l'envie de te prendre la tête, c'est pas un souci.

Bonne journée,
Pascal

**Comment by kwyxz** [comment]
Hello,

Je ne sais pas comment tu t'y es pris pour récupérer le script, mais si j'en crois les erreurs que je vois tu as téléchargé la page Github qui contient le script et pas le script lui-même.

Essaie avec ce lien : https://raw.githubusercontent.com/kwyxz/GetWindowsWallpapers/master/GetWindowsWallpapers.ps1

Et là ça doit fonctionner. A+

**Comment by kwyxz** [comment]
PS: pas besoin de lancer le script en administrateur

**Comment by Chwarma** [comment]
Merci pour tes réponses. J'essaie ça ce soir, je n'ai pas de windows 10 sous la main au taf.
Pour info, j'ai fait un clic droit sur le script puis j'ai téléchargé le lien. mea culpa
